### ISSUE TITLE
OS X version issue

### ISSUE THREAD

**Issue by PabloMontero** [wjakob/instant-meshes#39]
"You have OS X 10.10.5. The application requieres OS X 10.11 or later."

Seriously? I cannot use de .app but I don't have the time or knowledge or the space in my hard-disk to download two softwares and compile...

Please, some help!

**Comment by wjakob** [comment]
Can you try again in 30mins or so? I just committed a change that relaxes the default OSX requirement, but it will take a bit for the build bots to catch up.

**Comment by PabloMontero** [comment]
I download the .app and by double-clicking it and opening the message continue the same. However, if I double-click and Show the package content, then I can open the application!

**Comment by PabloMontero** [comment]
Still getting this icon.

<img width="538" alt="screen shot 2016-10-29 at 11 59 37" src="https://cloud.githubusercontent.com/assets/22867200/19828756/38b996cc-9dcf-11e6-9f31-7ace31c6aabf.png">

**Comment by raw915** [comment]
Is there a version that runs on OS X 10.10.5? For other reasons I cannot update to OS X 10.11 or later right now. Otherwise I'll have to look for something else.

**Comment by wjakob** [comment]
It's difficult for us to provide builds that are compatible with older OSX versions.
(The builds are automatic and done via AppVeyor, which always uses the latest XCode)

**Comment by wjakob** [comment]
You can of course compile Instant Meshes yourself for any version of OSX

**Comment by gormanj** [comment]
If anyone has a link to an older OS X build. This would be very much appreciated. I also need to run on OS 10.10. Unfortunately most Macs run into OS version limits from Apple.

**Comment by schroef** [comment]
Why not add releases so old build will still be available for download. Im still at 10.11.6 and it needs 10.12 :(

PS do i need Xcode or so for the compiling?

**Comment by schroef** [comment]
Ps there is something weird going on. I did try some methods to get it running and using the app itself results in this error.
<img width="532" alt="screen shot 2019-01-19 at 15 05 57" src="https://user-images.githubusercontent.com/6923008/51431201-ff91d780-1bfb-11e9-8f9f-0ce7b9faf315.png">


However i then went on to check if anything was noted in your plist about this, so added a lower minimum and tried that, still nothing.

Than i simply run the unix app inside the app content folder and it simple starts on OSX 10.11.6 without any warning???
<img width="1296" alt="screen shot 2019-01-19 at 15 06 04" src="https://user-images.githubusercontent.com/6923008/51431204-03bdf500-1bfc-11e9-9be8-cdbcaab05ab8.png">
